# Generated by Django 5.2.6 on 2025-10-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work08', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
